### ISSUE TITLE
Test mode

### ISSUE THREAD

**Issue by cmmh** [tinic/lightguy#1]
Any chance of getting a really basic test mode activate.  For example, rotate through the colors, with fading through the colors being an extra nice to have?

**Comment by tinic** [comment]
Check out the most recent firmware. I've added a "Startup Mode" option to the strip configuration. The device will go out of this mode as soon as it receives ArtNet/E1.31 data. My thinking is that this is more practical during physical setup than an explicit test mode.

In addition to the solid color as before, the new options are "Rainbow", "Tracer" and "Solid Tracer".

**Comment by tinic** [comment]
https://github.com/tinic/lightkraken/releases/download/latest/lightkraken-bin-2021-11-10-r336.zip

Flash the lightkraken_bootloaded.bin file (NOT lightkraken_bootloader.bin)

**Comment by cmmh** [comment]
Awesome, will give it a try.  Using the lightkraken as part of my holiday show as well as pixel checkout, so this will be a nice addition.
